// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMiJ0zMLSQXNbs_PO1xklDToLd4jiHtOg',
    appId: '1:884399228159:web:5b29d9c02c63881c6ff8ca',
    messagingSenderId: '884399228159',
    projectId: 'crud-dd5c6',
    authDomain: 'crud-dd5c6.firebaseapp.com',
    storageBucket: 'crud-dd5c6.appspot.com',
    measurementId: 'G-QT8YX5QW99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJpjJvPkwVmzGBNLiwXPbGuaAb5FxzS0',
    appId: '1:884399228159:android:e8822b6d28ef2aa46ff8ca',
    messagingSenderId: '884399228159',
    projectId: 'crud-dd5c6',
    storageBucket: 'crud-dd5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9_6kPasajeIsDzFGwN8kQYk-3fwWnTeM',
    appId: '1:884399228159:ios:17678fd5a3f5210d6ff8ca',
    messagingSenderId: '884399228159',
    projectId: 'crud-dd5c6',
    storageBucket: 'crud-dd5c6.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9_6kPasajeIsDzFGwN8kQYk-3fwWnTeM',
    appId: '1:884399228159:ios:74941318215b01d46ff8ca',
    messagingSenderId: '884399228159',
    projectId: 'crud-dd5c6',
    storageBucket: 'crud-dd5c6.appspot.com',
    iosBundleId: 'com.example.crudOperations.RunnerTests',
  );
}
